table _Measures
	lineageTag: 33d81e02-2997-4d01-8bb3-853691cbe4b4

	measure 'Sales Amount ($)' = SUM ( 'Fact Internet Sales'[SalesAmount] )
		formatString: #,0
		lineageTag: 6c3660cd-467c-4441-81c8-13fa46db9ed9

	measure 'Quantity (#)' = SUM ( 'Fact Internet Sales'[OrderQuantity] )
		formatString: 0
		lineageTag: a0269769-75ca-4b45-ad70-d327c4984011

	measure 'Discount Amount ($)' = SUM ( 'Fact Internet Sales'[DiscountAmount] )
		formatString: #,0.00
		lineageTag: f4eb798a-6e2a-4617-a80a-7039a307e645

	measure 'Sales Records (#)' = COUNTROWS ( 'Fact Internet Sales' )
		formatString: #,0
		lineageTag: 5a7ac133-1372-4e77-a040-af1fbeee77b6

	column Column1
		dataType: string
		isHidden
		lineageTag: 4eb0cf6a-6401-4ab7-9423-a2a0278c098d
		summarizeBy: none
		sourceColumn: Column1

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition _Measures = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

