name: Best Practice Analyzer
  
on:

  pull_request:
    branches: 
      - main
      - feature*      
    paths:
      - '**/*.SemanticModel/**'
  
  workflow_dispatch:
        
jobs:
  
  bpa:   
    runs-on: windows-latest
    
    steps:
        - name: Check out the code
          uses: actions/checkout@v4

        - name: Check all semantic models
          shell: pwsh
          run: .\scripts\bpa-model.ps1 -path "." -src "./*.SemanticModel"